services:
  database:
    image: player-image
    ports:
      - "5432:5432"
    env_file:
      - path: .env
        required: true
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
